### ISSUE TITLE
Comma breaks keyword highlighting in chained declarations

### ISSUE THREAD

**Issue by FreHu** [pvl/abap.tmbundle#32]
![code_2018-10-09_13-49-40](https://user-images.githubusercontent.com/5097067/46667540-39e5e480-cbca-11e8-8ec1-4ce8a8bfef78.png)

**Comment by larshp** [comment]
ABAP is a difficult language from a parsing perspective 😄

**Comment by FreHu** [comment]
Yeah, so many syntax variations for everything. I asked about a reference grammar, but apparently there is none, just bits you can get from the keyword documentation.

**Comment by larshp** [comment]
I've made this: https://larshp.github.io/abaplint/viz/ but it is not complete and contains lots of wrong stuff

**Comment by FreHu** [comment]
That's actually super cool, but I'll probably never get to doing individual keyword syntaxes. Even #29 will probably take significant effort since the grammar mostly just does "if it can be a keyword, make it a keyword". 

I'd be happy if at least the more modern ABAP was correctly highlighted - it is probably 99% of ABAP code which will ever make it into a git repository. On the other side, it wouldn't be useless as there are benefits to versioning legacy code as well (not as much incentive by its developers though).

Have you ever looked into implementing a [language server protocol](https://langserver.org/) for ABAP? It seems to be very reusable and would allow for some major stuff like goto definition or find references across editors and in github sources as well.

**Comment by larshp** [comment]
langserver: yes, I'm heading in that direction with abaplint 😄 it is just _a lot_ of work, getting the railroad diagrams is one thing, but building ASTs, integrating it into VS Code, lots of things to do, and I suck at writing parsers and doing TypeScript. But it will get there, first step is implementing the linting part as an extension in VS Code, I just keep getting distracted with other missing features

**Comment by larshp** [comment]
@FreHu published, https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint

**Comment by FreHu** [comment]
Downloaded. You should add some icons for free style points, your extensions will be among the first alphabetically.

![code_2018-10-20_11-28-13](https://user-images.githubusercontent.com/5097067/47253952-4a644d80-d45b-11e8-8a09-f65a79fde453.png)

**Comment by larshp** [comment]
yeah, but I dont feel very artistic, also icon for https://github.com/abaplint is crap 💩
