### ISSUE TITLE
LINES is not recognized in APPEND LINES OF

### ISSUE THREAD

**Issue by rlawisch** [pvl/abap.tmbundle#65]
LINES is not recognized
![code](https://user-images.githubusercontent.com/25728000/74987260-89bcf880-5419-11ea-81b5-ba18a0efe2ee.png)

Also, the returning variable is named return as my team's convention, and it is highlighted as a statement in this line (it usually is recognized as a variable).

**Comment by larshp** [comment]
thanks, pull requests welcome

**Comment by FreHu** [comment]
- lines is just a missing keyword
- variables named like keywords unfortunately have this problem because the grammar is very rough. although `result` is only used as a keyword in transformations i think, at least this could be special cased
