### ISSUE TITLE
Class definition is not higlighted correctly

### ISSUE THREAD

**Issue by FreHu** [pvl/abap.tmbundle#9]
It seems keywords after the class name and before the ending dot are colored the same as the name.

```abap
CLASS testclass definition
  public
  abstract
  create public.

  public section.
ENDCLASS.
```

![image](https://user-images.githubusercontent.com/5097067/41295262-6c9f9b50-6e5a-11e8-9d1e-27d492e79b12.png)

**Comment by larshp** [comment]
github also uses this grammar, see https://github.com/github/linguist/blob/master/vendor/README.md
