### ISSUE TITLE
how i debug 

### ISSUE THREAD

**Issue by saberabdelhady** [pvl/abap.tmbundle#99]
If anyone works with ABAP on VSCode, I create a program and activate it, everything is fine. But how can I also run and debug my own code in VSCode?

ctl+f5 not work
![image](https://github.com/pvl/abap.tmbundle/assets/39088480/fbb0aa0e-6264-4347-ab88-fb49fd1a247e)

**Comment by larshp** [comment]
Hi,
This repository is related to ABAP highlighting, and as such your question is off topic here.

But you either need a real system, alternatively https://github.com/abaplint/transpiler which is also used on https://exercism.org/tracks/abap

closing as off topic
